#!/bin/bash

source ./utils.sh

# for each .mp3 file in audio/tts directory, start a new process with ./run.sh

function fake() {
  for f in audio/tts/*.mp3; do
      CMD="./run.sh fake video/smale.mp4 $f"
      echo "$(date) $CMD" >> run.log
      eval $CMD
      # check the result and log result to file run.log
      if [ $? -eq 0 ]; then
          echo "$(date) Success" >> run.log
      else
          echo "$(date) Failed" >> run.log
          exit 1
      fi

  done
}

function cropFinalVideos() {
  appVideoDir="result/"
  dialogVideoDir="result/dialog/"
  checkedCount=0
  croppedCount=0
  for f in $appVideoDir*.mp4; do
    #将f中的appVideoDir替换为dialogVideoDir
    dialogVideoName=${f/$appVideoDir/$dialogVideoDir}
    cropFinalVideo $f $dialogVideoName
    #将返回值转为整数
    result=$(($?))

    checkedCount=$((checkedCount+1))
    if [ $result -eq 0 ]; then
      croppedCount=$((croppedCount+1))
    elif [ $result -eq -1 ]; then
      echo "Failed to crop $f to $dialogVideoName"
      echo "checkedCount: $checkedCount, croppedCount: $croppedCount"
      exit 1
    fi
  done
  echo "checkedCount: $checkedCount, croppedCount: $croppedCount"
}

#根据第一个参数选择功能：fake, cropFinalVideo
if [ $1 == "fake" ]; then
    # fake: 合成视频
    # $2: 视频文件
    # $3: 音频文件
    ffmpeg -i $2 -i $3 -c:v copy -c:a aac -strict experimental -map 0:v:0 -map 1:a:0 -shortest output.mp4
elif [ $1 == "crop" ]; then
    cropFinalVideos
else
    echo "Unknown command"
    exit 1
fi