#!/bin/bash

source ./utils.sh


cd "$(dirname "$0")"

logFile=./log/$(date +%Y%m%d).log
echo "$(date) start regression..." >> $logFile
setInRegression

echo $isInRegression
examVideos=$(getFileListInDirWhichHasPrefix "materials" "exam")
canVideos=$(getFileListInDirWhichHasPrefix "materials" "can")
qnaAudios=$(getFileListInDirWhichHasPrefix "materials" "qna-part1audio001")
echo "examVideos: $examVideos" >> $logFile
echo "canVideos: $canVideos" >> $logFile
echo "qnaAudios: $qnaAudios" >> $logFile

genratedCounter=0
skippedCounter=0
materialPath="materials/"
#遍历examVideos，canVideos，qnaAudios，调用generate脚本
for examVideo in $examVideos
do
  for canVideo in $canVideos
  do
    for qnaAudio in $qnaAudios
    do
      echo "checking $examVideo $canVideo $qnaAudio..." >> $logFile
      if [ $(isMaterialSeqLaterThan $qnaAudio "qna-008") == "false" ]; then
        echo "$qnaAudio is not later than qna-008, skip" >> $logFile
        continue
      fi
      echo "check result of materials: $examVideo $canVideo $qnaAudio" >> $logFile
      if [ $(isResultFileExistByMaterials $examVideo $canVideo $qnaAudio) = "true" ]; then
        echo "result file exist, skip" >> $logFile
        skippedCounter=$(($skippedCounter+1))
        continue
      fi
      if [ $(isReasonableMaterialsCombination $examVideo $canVideo $qnaAudio) = "false" ]; then
        echo "materials combination is not reasonable, skip" >> $logFile
        continue
      fi
      ./run $materialPath$examVideo $materialPath$canVideo $materialPath$qnaAudio
      if [ $? -ne 0 ]; then
        echo "generate failed, exit" >> $logFile
        exit 1
      fi
      genratedCounter=$(($genratedCounter+1))
      echo "$genratedCounter new files has been generated, $skippedCounter files has been skipped" >> $logFile
    done
  done
done
echo "[Report]: $genratedCounter new files generated" >> $logFile
unsetInRegression