#!/bin/bash

logFile=./log/$(date +%Y%m%d).log
if [ $# -eq 0 ]; then
  ./run.sh "help"
else
  #如果有参数，则执行main函数
  echo "[$(date)] $@" >> $logFile
  ./run.sh "main" "$@"
  if [ $? -ne 0 ]; then
    failInfo="./generate $@ failed"
    echo "!!! "$failInfo" !!!"
    echo "[$(date)] $failInfo" >> $logFile
    exit 1
  fi
fi
